#activemq
#spring.activemq.brokerUrl=tcp://127.0.0.1:61616
#spring.activemq.user=admin
#spring.activemq.password=admin
server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat
    trust-store: classpath:trust.key.p12
    trust-store-password: 123456
    client-auth: need
    trust-store-type: JKS
    trust-store-provider: SUN